### ISSUE TITLE
Sortcut variant and bucket size

### ISSUE THREAD

**Issue by jsmith1915** [lucidrains/sinkhorn-transformer#19]
From the paper it looks to me that for the sortcut variant, the queries are allowed to attend to all the key buckets post truncation for the non-causal case. If this is correct, won't the output be the same no matter what the bucket size is for the query.

Based on my understanding of the paper, the authors only report results selecting 2 top key/value blocks with bucket sizes 8,16,32. They do not mention having different bucket sizes for query and key/value which I found in this repo.

**Comment by jsmith1915** [comment]
Is allowing different bucket size for q and k_v enabled to ensure that memory and computation is not wasted by repeating the truncated sequence again and again for each query bucket. 

So is setting bucket_size to max_seq_len and kv_bucket_size to the actual bucket size we want, the correct way of using the sortcut variant?

**Comment by lucidrains** [comment]
@jsmith1915 that is correct! the query bucket size will not matter in the sortcut variant

Much of the difference from the paper is my own exploration into making this architecture work for my own practical use cases.

I worried that datasets with high variability in sequence lengths would lead to poor generalization of the sorting heads, if the bucket size was not clamped between a min/max window size. Thus I deviated from the paper and decided to make the network center on using a fixed bucket size rather than a fixed number of buckets. The alternative would have been to always pad all sequences to some minimum or maximum length to enforce some acceptable window size.

As for my efforts to separate the bucket sizes for queries and key/values, this is relevant for some image to caption encoder/decoder tasks, where the source and target sequences may be wildly different in length. I wanted finer control over how much attention each chunk of query could pay attention to, especially after I complete the feature where I can sort topk key/value buckets to one query bucket, rather than the 1 at the moment.

**Comment by jsmith1915** [comment]
Got it. For the simple sort net I see that you apply the sorting operation on a bucketed sequence with the key and query vector concatenated. 

In the paper didn't they learn the sorting on the bucketed input sequence to the attention layer before the q, k, v transformation, thus limiting their method only to self attention. 

Did you introduce concatenating key and query vectors to extend the method to encoder-decoder attention as well?

**Comment by lucidrains** [comment]
Yes! That was exactly my line of thinking

**Comment by jsmith1915** [comment]
If the query length is much smaller than key length, isn't it possible then that the SimpleSortNet followed by reordering would result in only one key bucket. For example, if the key sequence is 10 times longer than the query sequence, and the key sequence is bucketed into 10 buckets this happens. 

Then if n_sortcut is greater than 1, wouldn't https://github.com/lucidrains/sinkhorn-transformer/blob/master/sinkhorn_transformer/sinkhorn_transformer.py#L452 cause the batch dimension to leak into the bucket size dimension?

**Comment by lucidrains** [comment]
1. you are correct, and I have also addressed that with some engineering. in the latest version upgrade, I have enabled the feature to be able to sort multiple key/value buckets to a single query bucket. this was needed both for greater training stability and the flaw that you noted. the hyperparameter is `n_top_buckets` and defaults to 2

2. the tokens are shifted to the 2nd dimension `bsz * self.n_sortcut`

**Comment by lucidrains** [comment]
@jsmith1915 I updated L452 to be a bit more clear

**Comment by jsmith1915** [comment]
Isn't the n_top_buckets feaure applicable only to the non-permutative case? If Sinkhorn iterations are used, won't this issue will still persist.

**Comment by lucidrains** [comment]
@jsmith1915 I don't think Sinkhorn works at all with contextual key/values. It can only work in self-attention encoder scenarios where the keys and queries are divided into equal number of buckets. The only alternative the paper offered is to use the sortcut method. That's why I moved away and devised the attention solution instead.

**Comment by jsmith1915** [comment]
Yes, I also think that might be the case. For the case where query sequence is multiple of the key sequence, repeating the queries for each key block might be a reasonable approach as the sorting is learned. 

Have you tested the Sinkhorn attention with contextual key/values when the query and key sequences are of the same length.

**Comment by lucidrains** [comment]
@jsmith1915 I think it wouldn't even make sense. In the paper, the simple linear sort net only takes in information about the keys. If you feed it the contextual keys, how would it know anything about the query to make a judgement about the alignment? (Unless if the task is simple enough that the alignment can be inferred easily)

**Comment by lucidrains** [comment]
@jsmith1915 I have a feeling the author went with the Sinkhorn method because the permutative constraints matched the algorithmic sort task they were working on. My intuition tells me that the constraint doesn't generalize to all problems

**Comment by lucidrains** [comment]
@jsmith1915 The most useful trick I learned from this paper turned out not to be Sinkhorn, but that differentiable reordering works very well in practice, as long as you have some way of generating the sorting matrix R

**Comment by lucidrains** [comment]
@jsmith1915 However, I will keep the gumbel Sinkhorn feature alive as long as this repository evolves, since it was the main expose of the paper

**Comment by lucidrains** [comment]
@jsmith1915 Using Sinkhorn to rank the buckets of key/values (sortcut) may also be replaced with a better method https://arxiv.org/abs/2002.08871 down the road

**Comment by lucidrains** [comment]
@jsmith1915 I fired off too many comments in a row lol
